### Numpy --- 02

In [21]:
import numpy as np

In [22]:
empty = np.empty((2))
print(empty)

[1.29853360e+063 4.53167322e+293]


In [23]:
# array of +numbers
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [24]:
# array of odd num
odd = np.arange(1,20,3)
print(odd)

[ 1  4  7 10 13 16 19]


In [25]:
lin = np.linspace(0, 10, num=20)
lin

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [26]:
# define the arr type
n = np.arange(0,22.2, 1.5, dtype=np.int64)
n = np.ones(0 ,dtype=np.int64)
n

array([], dtype=int64)

Assignment: What is the difference between int32, 64... ya flot 32.. in ka matlab?

In [27]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,7,8,9,10])

In [28]:
# concatenate the arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

Concatenate 2D array

In [29]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[40,50,60]])

# concate 2D array
z = np.concatenate((x,y))
z


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [40, 50, 60]])

In [30]:
w = np.array([[1,1],[2,2]])
w2 = np.array([[1,1],[2,2]])

w3 = np.concatenate((w,w2), axis=1)
w3

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [31]:
# create a 3D array

array_3d = np.array(
    [[[1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]],
    
    [[1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]]])

array_3d.ndim

3

In [36]:
a.reshape(3,1,2)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

# indexig and slicing 

In [67]:
index_slice = np.array([[1,2,3,4],[5,6,7,8],[50,60,71,80]])

# index_slice[1,3]
index_slice[index_slice>5]

# even number filteration
index_slice[index_slice % 2 ==0]

# filter odd nums
index_slice[index_slice % 2 ==1]

# make two condition
index_slice[(index_slice < 5) & (index_slice > 50)]

array([], dtype=int32)