## Numpy Indexing

In [9]:
import numpy as np


a = np.array([1,2,3,4,5,6,7])

In [10]:
a[0]

1

In [12]:
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [20]:
b[2]

c = b.reshape(3,2)
# c[0]
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [25]:
d = np.arange(0,222,5)
d

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [27]:
arr1 = d[30:50]
arr1

array([150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210,
       215, 220])

In [30]:
# d = np.vstack((a,b))
# d

Matrix or Matrices

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# large dimension matrix
a1 = np.arange(0,100,2).reshape(10,5)
a1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [43]:
a1.max(axis=0)

array([90, 92, 94, 96, 98])

In [44]:
a1.max(axis=1)

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])