In [2]:
import numpy as np

In [18]:
a = np.arange(9)
print(a)
a.shape

[0 1 2 3 4 5 6 7 8]


(9,)

In [16]:
b = a[np.newaxis, : ]
# b = a[: ,np.newaxis ]
print(b)

[[0 1 2 3 4 5 6 7 8]]


In [17]:
b.shape

(1, 9)

In [24]:
c = np.array([1,2,3,4,5,6])
# c1 = np.array([[1,2,3,4,5,6],[4,5,6,7,7,8,9]])
c1 = np.array([[1,2,3,4,5,6], [4,5,6,7,8,9]])
c1.shape

(2, 6)

In [29]:
d = np.full((2,5),3)
print(d)

[[3 3 3 3 3]
 [3 3 3 3 3]]
